name: Unit Tests

on: 
  workflow_dispatch:
  pull_request:
  push:

jobs:
  test:
    strategy: 
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.0", "3.1", "3.2", "3.3", "3.4", "3.5", "3.6", "3.7", "3.8", "3.9", "3.10"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with: 
          python-version: ${{ matrix.python-version }}
      - run: python -m pip install black
      - name: Lint with Black
        run: python -m black --check .
      - name: Test with unittest
        run: python -m unittest